config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :student_booking_in_classes
  resources :bookings
  resources :student_in_classes
  resources :class_colleges
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/articles", to: "articles#index"
  
end

app/models/class_college.rb
class ClassCollege < ApplicationRecord
end

app/controllers/class_colleges_controller.rb
class ClassCollegesController < ApplicationController
  before_action :set_class_college, only: %i[ show edit update destroy ]

  # GET /class_colleges or /class_colleges.json
  def index
    @class_colleges = ClassCollege.all
  end

  # GET /class_colleges/1 or /class_colleges/1.json
  def show
  end

  # GET /class_colleges/new
  def new
    @class_college = ClassCollege.new
  end

  # GET /class_colleges/1/edit
  def edit
  end

  # POST /class_colleges or /class_colleges.json
  def create
    @class_college = ClassCollege.new(class_college_params)

    respond_to do |format|
      if @class_college.save
        format.html { redirect_to @class_college, notice: "Class college was successfully created." }
        format.json { render :show, status: :created, location: @class_college }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @class_college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_colleges/1 or /class_colleges/1.json
  def update
    respond_to do |format|
      if @class_college.update(class_college_params)
        format.html { redirect_to @class_college, notice: "Class college was successfully updated." }
        format.json { render :show, status: :ok, location: @class_college }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @class_college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_colleges/1 or /class_colleges/1.json
  def destroy
    @class_college.destroy

    respond_to do |format|
      format.html { redirect_to class_colleges_path, status: :see_other, notice: "Class college was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_college
      @class_college = ClassCollege.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def class_college_params
      params.require(:class_college).permit(:id_user, :id_schedule, :id_student_in_class, :year, :class_shift, :max_number_students, :id_subject)
    end
end

app/helpers/class_colleges_helper.rb
module ClassCollegesHelper
end

app/views/class_colleges/_form.html.erb
<%= form_with(model: class_college, local: true) do |form| %>
  <% if class_college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_college.errors.count, "error") %> prohibited this class_college from being saved:</h2>

      <ul>
      <% class_college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_user %>
    <%= form.number_field :id_user %>
  </div>

  <div class="field">
    <%= form.label :id_schedule %>
    <%= form.number_field :id_schedule %>
  </div>

  <div class="field">
    <%= form.label :id_student_in_class %>
    <%= form.number_field :id_student_in_class %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year %>
  </div>

  <div class="field">
    <%= form.label :class_shift %>
    <%= form.number_field :class_shift %>
  </div>

  <div class="field">
    <%= form.label :max_number_students %>
    <%= form.number_field :max_number_students %>
  </div>

  <div class="field">
    <%= form.label :id_subject %>
    <%= form.number_field :id_subject %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_colleges/edit.html.erb
<h1>Editing Class College</h1>

<%= render 'form', class_college: @class_college %>

<%= link_to 'Show', @class_college %> |
<%= link_to 'Back', class_colleges_path %>

app/views/class_colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Id schedule</th>
      <th>Id student in class</th>
      <th>Year</th>
      <th>Class shift</th>
      <th>Max number students</th>
      <th>Id subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_colleges.each do |class_college| %>
      <tr>
        <td><%= class_college.id_user %></td>
        <td><%= class_college.id_schedule %></td>
        <td><%= class_college.id_student_in_class %></td>
        <td><%= class_college.year %></td>
        <td><%= class_college.class_shift %></td>
        <td><%= class_college.max_number_students %></td>
        <td><%= class_college.id_subject %></td>
        <td><%= link_to 'Show', class_college %></td>
        <td><%= link_to 'Edit', edit_class_college_path(class_college) %></td>
        <td><%= link_to 'Destroy', class_college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class College', new_class_college_path %>

app/views/class_colleges/new.html.erb
<h1>New Class College</h1>

<%= render 'form', class_college: @class_college %>

<%= link_to 'Back', class_colleges_path %>

app/views/class_colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @class_college.id_user %>
</p>

<p>
  <strong>Id schedule:</strong>
  <%= @class_college.id_schedule %>
</p>

<p>
  <strong>Id student in class:</strong>
  <%= @class_college.id_student_in_class %>
</p>

<p>
  <strong>Year:</strong>
  <%= @class_college.year %>
</p>

<p>
  <strong>Class shift:</strong>
  <%= @class_college.class_shift %>
</p>

<p>
  <strong>Max number students:</strong>
  <%= @class_college.max_number_students %>
</p>

<p>
  <strong>Id subject:</strong>
  <%= @class_college.id_subject %>
</p>

<%= link_to 'Edit', edit_class_college_path(@class_college) %> |
<%= link_to 'Back', class_colleges_path %>