config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :student_booking_in_classes
  resources :bookings
  resources :student_in_classes
  resources :class_colleges
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/articles", to: "articles#index"
  
end

app/controllers/student_booking_in_classes_controller.rb
class StudentBookingInClassesController < ApplicationController
  before_action :set_student_booking_in_class, only: %i[ show edit update destroy ]

  # GET /student_booking_in_classes or /student_booking_in_classes.json
  def index
    @student_booking_in_classes = StudentBookingInClass.all
  end

  # GET /student_booking_in_classes/1 or /student_booking_in_classes/1.json
  def show
  end

  # GET /student_booking_in_classes/new
  def new
    @student_booking_in_class = StudentBookingInClass.new
  end

  # GET /student_booking_in_classes/1/edit
  def edit
  end

  # POST /student_booking_in_classes or /student_booking_in_classes.json
  def create
    @student_booking_in_class = StudentBookingInClass.new(student_booking_in_class_params)

    respond_to do |format|
      if @student_booking_in_class.save
        format.html { redirect_to @student_booking_in_class, notice: "Student booking in class was successfully created." }
        format.json { render :show, status: :created, location: @student_booking_in_class }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_booking_in_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_booking_in_classes/1 or /student_booking_in_classes/1.json
  def update
    respond_to do |format|
      if @student_booking_in_class.update(student_booking_in_class_params)
        format.html { redirect_to @student_booking_in_class, notice: "Student booking in class was successfully updated." }
        format.json { render :show, status: :ok, location: @student_booking_in_class }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_booking_in_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_booking_in_classes/1 or /student_booking_in_classes/1.json
  def destroy
    @student_booking_in_class.destroy

    respond_to do |format|
      format.html { redirect_to student_booking_in_classes_path, status: :see_other, notice: "Student booking in class was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_booking_in_class
      @student_booking_in_class = StudentBookingInClass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_booking_in_class_params
      params.require(:student_booking_in_class).permit(:id_user, :id_student_in_class, :class_shift)
    end
end

app/helpers/student_booking_in_classes_helper.rb
module StudentBookingInClassesHelper
end

app/views/student_booking_in_classes/_form.html.erb
<%= form_with(model: student_booking_in_class, local: true) do |form| %>
  <% if student_booking_in_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_booking_in_class.errors.count, "error") %> prohibited this student_booking_in_class from being saved:</h2>

      <ul>
      <% student_booking_in_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_user %>
    <%= form.number_field :id_user %>
  </div>

  <div class="field">
    <%= form.label :id_student_in_class %>
    <%= form.number_field :id_student_in_class %>
  </div>

  <div class="field">
    <%= form.label :class_shift %>
    <%= form.number_field :class_shift %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_booking_in_classes/edit.html.erb
<h1>Editing Student Booking In Class</h1>

<%= render 'form', student_booking_in_class: @student_booking_in_class %>

<%= link_to 'Show', @student_booking_in_class %> |
<%= link_to 'Back', student_booking_in_classes_path %>

app/views/student_booking_in_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Booking In Classes</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Id student in class</th>
      <th>Class shift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_booking_in_classes.each do |student_booking_in_class| %>
      <tr>
        <td><%= student_booking_in_class.id_user %></td>
        <td><%= student_booking_in_class.id_student_in_class %></td>
        <td><%= student_booking_in_class.class_shift %></td>
        <td><%= link_to 'Show', student_booking_in_class %></td>
        <td><%= link_to 'Edit', edit_student_booking_in_class_path(student_booking_in_class) %></td>
        <td><%= link_to 'Destroy', student_booking_in_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Booking In Class', new_student_booking_in_class_path %>

app/views/student_booking_in_classes/new.html.erb
<h1>New Student Booking In Class</h1>

<%= render 'form', student_booking_in_class: @student_booking_in_class %>

<%= link_to 'Back', student_booking_in_classes_path %>

app/views/student_booking_in_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @student_booking_in_class.id_user %>
</p>

<p>
  <strong>Id student in class:</strong>
  <%= @student_booking_in_class.id_student_in_class %>
</p>

<p>
  <strong>Class shift:</strong>
  <%= @student_booking_in_class.class_shift %>
</p>

<%= link_to 'Edit', edit_student_booking_in_class_path(@student_booking_in_class) %> |
<%= link_to 'Back', student_booking_in_classes_path %>